import 'package:flutter/material.dart';

class SizeConfig {
  static MediaQueryData? _mediaQueryData;
  static double? screenHeight;
  static double? height1;
  static double? height2;
  static double? height3;
  static double? height4;
  static double? height5;
  static double? height6;
  static double? height7;
  static double? height8;
  static double? height9;
  static double? height10;
  static double? height20;
  static double? height30;
  static double? height40;
  static double? height50;
  static double? height60;
  static double? height70;
  static double? screenWidth;
  static double? width1;
  static double? width2;
  static double? width3;
  static double? width4;
  static double? width5;
  static double? width6;
  static double? width7;
  static double? width8;
  static double? width9;
  static double? width10;
  static double? width15;
  static double? width20;
  static double? width25;
  static double? width30;
  static double? width35;
  static double? width40;
  static double? width45;
  static double? width50;
  static double? width55;
  static double? width60;
  static double? width70;

  static double? blocSizeHorizontal;
  static double? blocSizeVertical;

  void init(BuildContext context) {
    _mediaQueryData = MediaQuery.of(context);
    screenWidth = _mediaQueryData?.size.width;
    screenHeight = _mediaQueryData?.size.height;
    height1 = screenHeight! / 1;
    height2 = screenHeight! / 2;
    height3 = screenHeight! / 3;
    height4 = screenHeight! / 4;
    height5 = screenHeight! / 5;
    height6 = screenHeight! / 6;
    height7 = screenHeight! / 7;
    height8 = screenHeight! / 8;
    height9 = screenHeight! / 9;
    height10 = screenHeight! / 10;
    height20 = screenHeight! / 20;
    height30 = screenHeight! / 30;
    height40 = screenHeight! / 40;
    height50 = screenHeight! / 50;
    height60 = screenHeight! / 60;
    height70 = screenHeight! / 70;
    width1 = screenWidth! / 1;
    width2 = screenWidth! / 2;
    width3 = screenWidth! / 3;
    width4 = screenWidth! / 4;
    width5 = screenWidth! / 5;
    width6 = screenWidth! / 6;
    width7 = screenWidth! / 7;
    width8 = screenWidth! / 8;
    width9 = screenWidth! / 9;
    width10 = screenWidth! / 10;
    width15 = screenWidth! / 15;
    width20 = screenWidth! / 20;
    width25 = screenWidth! / 25;
    width30 = screenWidth! / 30;
    width35 = screenWidth! / 35;
    width40 = screenWidth! / 40;
    width45 = screenWidth! / 45;
    width50 = screenWidth! / 50;
    width55 = screenWidth! / 55;
    width60 = screenWidth! / 60;
    width70 = screenWidth! / 70;
    blocSizeHorizontal = screenWidth! / 100;
    blocSizeVertical = screenHeight! / 100;
  }
}
